apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: emg1etv9j-go-gitops
  description: This is GitOps manifest for emg1etv9j-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=emg1etv9j-go
    backstage.io/kubernetes-id: emg1etv9j-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: emg1etv9j-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:emg1etv9j-go
