apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: emg1etv9j-go
  janus-idp.io/tekton: emg1etv9j-go
  backstage.io/kubernetes-id: emg1etv9j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: emg1etv9j-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
